# Generated by Django 4.2.7 on 2024-11-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legalquestion",
            options={},
        ),
        migrations.AddField(
            model_name="legalquestion",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalquestion",
            name="processing_time",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="legalquestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает ответа"),
                    ("answered", "Отвечен"),
                    ("failed", "Ошибка"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="legalquestion",
            index=models.Index(
                fields=["user", "created_at"], name="legal_app_l_user_id_29a3b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="legalquestion",
            index=models.Index(
                fields=["category"], name="legal_app_l_categor_5abae3_idx"
            ),
        ),
    ]
